routes/web.php
<?php
//testing
Route::get('/demo/schedule', function(){
	return view('Page.Schedule.index_bc');
});
Route::get('/demo/schedule/week', function(){
	return view('Page.Schedule.week_bc');
});
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/welcome', function() {
	return view('welcome');
});
Route::get('/fire', function(){
	\Event::fire(new App\Events\TestEvent(1));
	return 'Event fired. Go to /show to observe.';
});

// Auth::routes();
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
// Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
// Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');


//Must Auth
Route::group(['middleware' => 'auth'], function() {

	//Dashbord / order
	Route::get('/', 'HomeController@index')->name('home');

	//Users
	Route::resource('user', 'UserController',['except' => ['edit']]);

	//Schedule
	Route::get('/schedule/{year?}/{month?}/', 'ScheduleController@month')->name('schedule.month');
	Route::get('/schedule/{year?}/{month?}/{date?}', 'ScheduleController@week')->name('schedule.week');

	//Orders
	Route::resource('order', 'OrderController',['except' => ['edit']]);
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        //$this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('Page.Order.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Page.Order.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('Page.Order.detail');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/ScheduleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
Use Carbon\Carbon;

class ScheduleController extends Controller
{

	private $current;

    public function __construct()
    {
    	$this->current = Carbon::now();
    }

    public function month($year = null, $month = null)
    {
    	$this->current = Carbon::createFromDate($year, $month);
    	return view('Page.Schedule.index')->with('currentDate', $this->current);
    }
    public function week($year = null, $month = null, $date=null)
    {
        $this->current = Carbon::createFromDate($year, $month, $date);
        return view('Page.Schedule.week')->with('currentDate', $this->current);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Validator;
use App\User;
use Alert;
use Auth;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = User::whereNotIn('id', [ 'id' => Auth::user()->id])->orderBy('created_at', 'desc')->get();
        return view('Page.User.index')->with('data', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Page.User.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:6',
        ]);
        bcrypt($request->input('password'));
        $user = User::create($request->input());

        if($user->save()){
            return "ok";
        }

        return "fails";

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('Page.User.form')->with('data', User::findOrFail($id));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users,email,'.$id,
            'password' => 'required|string|min:6',
        ]);

        $data = User::findOrFail($id);
        $data->name = $request->input('name');
        $data->email = $request->input('email');
        $data->password = bcrypt($request->input('password'));

        if($data->save()){
            Alert::success('User has been updated');
            return $this->index();
        }else{
            Alert::danger('Ops sorry, something wrong');
            return back();
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        
        if(User::destroy($id)){
            Alert::success('Data telah terhapus');
            return $this->index();
        }
        
        Alert::danger('Somthinf wrong !');
        return back();

    }
}

resources/views/Page/Order/index.blade.php
@extends('layouts.app')

@section('content')
<div class="page-container">
	<div class="container">
		<div class="row">
		<div class="col-md-12">
			<h3>Order List <a href="{{ route('order.create') }}" class="btn btn-success pull-right">Buat Order Baru</a></h3>

		</div>
		<div class="col-md-12">

			<div class="panel panel-default">
				<div class="panel-heading"></div>
				<div class="panel-body">
						<table class="table">
							<thead>
								<tr>
									<th>No. PO</th>
									<th>Kapten</th>
									<th>Pemesan</th>
									<th>Jumlah</th>
									<th class="text-right">Total</th>
									<th class="text-center">Pengiriman</th>
									<th class="text-center">Tgl PO</th>
									<th class="text-center">Status</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td><a href="{{ route('order.show', ['id'=>'0008813']) }}">0008813</a></td>
									<td>Kapten 1</td>
									<td>PT. Purnama</td>
									<td>1200 l</td>
									<td class="text-right">Rp. 9.024.000,-</td>
									<td class="text-center">Semarang, 28-10-2017</td>
									<td class="text-center">19-9-2017</td>
									<td class="text-center"><span class="label label-info">Waiting</span></td>
								</tr>	
								<tr>
									<td><a href="{{ route('order.show', ['id'=>'0008813']) }}">0008813</a></td>
									<td>Kapten 1</td>
									<td>PT. Purnama</td>
									<td>1200 l</td>
									<td class="text-right">Rp. 9.024.000,-</td>
									<td class="text-center">Semarang, 28-10-2017</td>
									<td class="text-center">19-9-2017</td>
									<td class="text-center"><span class="label label-success">On Progress</span></td>
								</tr>	
								<tr>
									<td><a href="{{ route('order.show', ['id'=>'0008813']) }}">0008813</a></td>
									<td>Kapten 1</td>
									<td>PT. Purnama</td>
									<td>1200 l</td>
									<td class="text-right">Rp. 9.024.000,-</td>
									<td class="text-center">Semarang, 28-10-2017</td>
									<td class="text-center">19-9-2017</td>
									<td class="text-center"><span class="label label-danger">Pending</span></td>
								</tr>
								<tr>
									<td><a href="{{ route('order.show', ['id'=>'0008813']) }}">0008813</a></td>
									<td>Kapten 1</td>
									<td>PT. Purnama</td>
									<td>1200 l</td>
									<td class="text-right">Rp. 9.024.000,-</td>
									<td class="text-center">Semarang, 28-10-2017</td>
									<td class="text-center">19-9-2017</td>
									<td class="text-center"><span class="label label-default">success</span></td>
								</tr>								
							</tbody>
						</table>	
				</div>
			</div>
		</div>
	</div>
	</div>
</div>
@endsection

resources/views/Page/Schedule/index.blade.php
@extends('layouts.app')

@section('content')
	<div class="container-fuild page-container full-height">
		<month
            prev="prev"
            next="next"
            now="{{ $currentDate }}"
        ></month>
	</div>	
@endsection

resources/views/Page/Schedule/week.blade.php
@extends('layouts.app')

@section('content')
  <div class="container-fuild page-container full-height">
    <week
            prev="prev"
            next="next"
            now="{{ $currentDate }}"
        ></week>
  </div>  
@endsection

resources/views/Page/User/form.blade.php
@extends('layouts.app')

@section('content')
<div class="page-container"></div>
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ isset($data) ? $data->name : 'Create User' }}
                    <span class="pull-right">
                        <a href="{{ route('user.index') }}">Back to list</a>
                    </span>
                </div>

                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="{{ isset($data) ? route('user.update',$data->id) : route('user.store') }}">
                        {!! isset($data) ? method_field('put') : '' !!}
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{ isset($data) ? $data->name : old('name') }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="col-md-4 control-label">E-Mail Address</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control" name="email" value="{{ isset($data) ? $data->email : old('email') }}" required>

                                @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="col-md-4 control-label">Role</label>

                            <div class="col-md-6">
                                <select class="form-control">
                                    <option>Kapten</option>
                                    <option>Admin</option>
                                    <option>Guest</option>
                                </select>

                                @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="password" class="col-md-4 control-label">Password</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control" value="{{ old('password') }}" name="password" required>

                                @if ($errors->has('password'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <!-- <div class="form-group">
                            <label for="password-confirm" class="col-md-4 control-label">Confirm Password</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                            </div>
                        </div> -->

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Register
                                </button>
                            </div>
                        </div>
                    </form>
                     @if(isset($data))
                        <form action="{{ route('user.destroy',$data->id) }}" method="POST">
                            {!! method_field('delete') !!}
                            {{ csrf_field() }}
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                        @endif
                </div>
            </div>
        </div>
    </div>
</div>
</div>
@endsection

resources/views/Page/User/index.blade.php
@extends('layouts.app')

@section('content')
<div class="page-container">
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">User List</div>
				<div class="panle-body">
						<table class="table">
							<thead>
								<tr>
									<th>Name</th>
									<th>Email</th>
									<th>Role</th>
									<th>Create at</th>
								</tr>
							</thead>
							<tbody>
								@foreach($data as $user)
									<tr>
										<td><a href="{{ route('user.show',$user->id) }}">{{ $user->name }}</a></td>
										<td>{{ $user->email }}</td>
										<td>Kapten</td>
										<td>{{ $user->created_at }}</td>
									</tr>
								@endforeach
							</tbody>
						</table>	
				</div>
			</div>
		</div>
	</div>
</div>
</div>
@endsection

resources/views/layouts/full.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Project Pati</title>

    <!-- Styles -->
    <link href="{{ asset('css/calendar.css') }}" rel="stylesheet">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        @include('alert::bootstrap')
        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/header.blade.php
<div class="header">
    <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        Project Pati
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <!-- <ul class="nav navbar-nav">
                        &nbsp;
                    </ul> -->

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Notification (<b>2</b>)</a>
                              <ul class="dropdown-menu notify-drop">
                                <div class="notify-drop-title">
                                    <div class="row">
                                        <div class="col-md-6 col-sm-6 col-xs-6">Bildirimler (<b>2</b>)</div>
                                        <div class="col-md-6 col-sm-6 col-xs-6 text-right"><a href="" class="rIcon allRead" data-tooltip="tooltip" data-placement="bottom" title="tümü okundu."><i class="fa fa-dot-circle-o"></i></a></div>
                                    </div>
                                </div>
                                <!-- end notify title -->
                                <!-- notify content -->
                                <div class="drop-content">
                                    <li>
                                        <div class="col-md-3 col-sm-3 col-xs-3"><div class="notify-img"><img src="http://placehold.it/45x45" alt=""></div></div>
                                        <div class="col-md-9 col-sm-9 col-xs-9 pd-l0"><a href="">Ahmet</a> yorumladı. <a href="">Çicek bahçeleri...</a> <a href="" class="rIcon"><i class="fa fa-dot-circle-o"></i></a>
                                        
                                        <hr>
                                        <p class="time">Şimdi</p>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="col-md-3 col-sm-3 col-xs-3"><div class="notify-img"><img src="http://placehold.it/45x45" alt=""></div></div>
                                        <div class="col-md-9 col-sm-9 col-xs-9 pd-l0"><a href="">Ahmet</a> yorumladı. <a href="">Çicek bahçeleri...</a> <a href="" class="rIcon"><i class="fa fa-dot-circle-o"></i></a>
                                        <p>Lorem ipsum sit dolor amet consilium.</p>
                                        <p class="time">1 Saat önce</p>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="col-md-3 col-sm-3 col-xs-3"><div class="notify-img"><img src="http://placehold.it/45x45" alt=""></div></div>
                                        <div class="col-md-9 col-sm-9 col-xs-9 pd-l0"><a href="">Ahmet</a> yorumladı. <a href="">Çicek bahçeleri...</a> <a href="" class="rIcon"><i class="fa fa-dot-circle-o"></i></a>
                                        <p>Lorem ipsum sit dolor amet consilium.</p>
                                        <p class="time">29 Dakika önce</p>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="col-md-3 col-sm-3 col-xs-3"><div class="notify-img"><img src="http://placehold.it/45x45" alt=""></div></div>
                                        <div class="col-md-9 col-sm-9 col-xs-9 pd-l0"><a href="">Ahmet</a> yorumladı. <a href="">Çicek bahçeleri...</a> <a href="" class="rIcon"><i class="fa fa-dot-circle-o"></i></a>
                                        <p>Lorem ipsum sit dolor amet consilium.</p>
                                        <p class="time">Dün 13:18</p>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="col-md-3 col-sm-3 col-xs-3"><div class="notify-img"><img src="http://placehold.it/45x45" alt=""></div></div>
                                        <div class="col-md-9 col-sm-9 col-xs-9 pd-l0"><a href="">Ahmet</a> yorumladı. <a href="">Çicek bahçeleri...</a> <a href="" class="rIcon"><i class="fa fa-dot-circle-o"></i></a>
                                        <p>Lorem ipsum sit dolor amet consilium.</p>
                                        <p class="time">2 Hafta önce</p>
                                        </div>
                                    </li>
                                </div>
                                <div class="notify-drop-footer text-center">
                                    <a href=""><i class="fa fa-eye"></i> Tümünü Göster</a>
                                </div>
                              </ul>
                            </li>
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                        @else
                            <li class="">
                                <a href="#" class="" data-toggle="" role="" aria-expanded="">
                                    {{ Auth::user()->name }}
                                </a>
                            </li>
                            <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                        @endif
                    </ul>
                </div>
            </div>
    </nav>
    <nav class="navbar navbar-default navbar-static-top header-menu">
            <div class="container">
                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{{ route('home') }}">Dashboard</a></li>
                        <li>
                            <a href="#" data-toggle="dropdown" role="button" aria-expanded="false">Schedule <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{{ route('schedule.month') }}">Month</a></li>
                                <li><a href="{{ route('schedule.week',['year'=>'2017', 'month'=>'09', 'date'=>'19']) }}">Week</a></li>
                            </ul>
                        </li>
                        <li><a href="{{ route('order.index') }}">Order</a></li>
                        <li><a href="#">Report</a></li>
                        <li><a href="{{ route('user.index') }}">User</a></li>
                        <li><a href="#">Setting</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Notification (<b>2</b>)</a>
                              <ul class="dropdown-menu notify-drop">
                                <div class="notify-drop-title">
                                    <div class="row">
                                        <div class="col-md-6 col-sm-6 col-xs-6">Order complete (<b>2</b>)</div>
                                        <div class="col-md-6 col-sm-6 col-xs-6 text-right"><a href="" class="rIcon allRead" data-tooltip="tooltip" data-placement="bottom" title="tümü okundu."><i class="fa fa-dot-circle-o"></i></a></div>
                                    </div>
                                </div>
                                <!-- end notify title -->
                                <!-- notify content -->
                                <div class="drop-content">
                                    <li>
                                        <div class="col-xs-12">
                                            <p class="bold">PO: 000623 - Konfirmasi</p>
                                            <p>Kapten 1 telah megirim konfirmasi pengiriman <a href="{{ route('order.show',['id'=>'009965']) }}">cek konfirmasi</a></p>
                                        
                                        <hr>
                                        <p class="time">1 minute ago</p>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="col-xs-12">
                                            <p class="bold">PO: 000623 - Pesan</p>
                                            <p>Kapten 2 - Ada kendala di kapal kami mungkin ini akan menghabat pengiriman .. <a href="{{ route('order.show',['id'=>'009965']) }}">baca</a></p>
                                        
                                        <hr>
                                        <p class="time">30 minute ago</p>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="col-xs-12">
                                            <p class="bold">PO: 000623 - Complete</p>
                                            <p>Admin 1 telah merubah status menjadi complete <a href="{{ route('order.show',['id'=>'009965']) }}">lihat order</a></p>
                                        
                                        <hr>
                                        <p class="time">1 hour ago</p>
                                        </div>
                                        <div class="col-xs-12">
                                            <p class="bold">PO: 000623 - Perubahan Jadwal</p>
                                            <p>Admin 3 telah merubah jadwal pengiriman <a href="{{ route('order.show',['id'=>'009965']) }}">lihat order</a></p>
                                        
                                        <hr>
                                        <p class="time">yesterday</p>
                                        </div>
                                    </li>
                                </div>
                                <div class="notify-drop-footer text-center">
                                    <a href=""><i class="fa fa-eye"></i> Lihat Semua</a>
                                </div>
                              </ul>
                            </li>
                            </ul>
                </div>
            </div>
    </nav>
</div>